export const SET_LOCALE = 'SET_LOCALE'

export const SIGN_IN_EMAIL_AUTH = 'SIGN_IN_EMAIL_AUTH'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const CREATE_ERROR = 'CREATE_ERROR'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

export const CLEAR_USERS = 'CLEAR_USERS'
